version: '3.1'
services:
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://pma.ceee.dev #optional
    volumes:
      - ./volume/phpmyadmin/config:/config
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - db-network 

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CUSTOM_PORT=5000
      - CUSTOM_HTTPS_PORT=5001
    volumes:
      - ./volume/mysql-workbench/config:/config
    ports:
      - 5000:5000
      - 5001:5001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - db-network 
      
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD}
      - MYSQL_DATABASE=${USER_DB_NAME} #optional
      - MYSQL_USER=${MYSQL_USER} #optional
      - MYSQL_PASSWORD=${DATABASE_PASSWORD} #optional
    volumes:
      - /volume/mariadb/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - db-network
  
  webtop: 
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBFOLDER=/ #optional
      - TITLE=Webtop-Ubuntu #optional
    volumes:
      - ./volume/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-db
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24

    
