---
services:
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://pma.ceee.dev #optional
    volumes:
      - ./volume/phpmyadmin/config:/config
    ports:
      - 80:80
    restart: unless-stopped

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./volume/mysql-workbench/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  percona-server:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306"
    volumes:
      # create volumes for use
      - ./volumes/percona-server/data/:/var/lib/mysql
      # bind mount my local my.cnf
      # - $PWD/my.cnf:/etc/my.cnf.d/my.cnf

# uncomment sections below if you want to enable PMM
  pmm-server:
    image: percona/pmm-server:latest
   ports:
     - "443:443"
   environment:
     - SERVER_USER=pmm
     - SERVER_PASSWORD=pmm
  pmm-client-ps:
    image: perconalab/pmm-client:latest
   environment:
     - PMM_SERVER=pmm-server:443
     - PMM_USER=pmm
     - PMM_PASSWORD=${MM_PASSWORD}
     - DB_TYPE=mysql
     - DB_HOST=percona-server
     - DB_PORT=3306
     - DB_USER=root
     - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    
