---
services:
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://pma.ceee.dev #optional
    volumes:
      - ./volume/phpmyadmin/config:/config
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - db-network 

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./volume/mysql-workbench/config:/config
    ports:
      - 3002:3000
      - 3003:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - db-network 

  percona-server:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # create volumes for use
      - ./volumes/percona-server/data/:/var/lib/mysql
      # bind mount my local my.cnf
      # ./volume/conf/my.cnf:/etc/my.cnf.d/my.cnf  networks:
    networks:
      - db-network   

# uncomment sections below if you want to enable PMM
  pmm-server:
    image: percona/pmm-server:latest
    ports:
      - "443:443"
    environment:
      - SERVER_USER=pmm
      - SERVER_PASSWORD=pmm
    networks:
      - db-network

  pmm-client-ps:
    image: perconalab/pmm-client:latest
    environment:
     - PMM_SERVER=pmm-server:443
     - PMM_USER=pmm
     - PMM_PASSWORD=${PMM_PASSWORD}
     - DB_TYPE=mysql
     - DB_HOST=percona-server
     - DB_PORT=3306
     - DB_USER=root
     - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
  networks:
    - db-network
  
  webtop: 
    image: lscr.io/linuxserver/ubuntu-openbox
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./volume/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-db
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

    
